postgres:
  conn_id: supermarket

views:
  - schema: report
    concurrently: false
    names:
      - commercial_performance_v2
      - exchange_rate
      - executive_overview_v2
      - finance_payment_performance_v2
      - user_experience_v2
